# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  pull_request:
    branches: ['*']

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: taskmanagement_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          TZ: UTC
          PGTZ: UTC
        options: --restart=unless-stopped

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3.1.1
        with:
          node-version: '16.X'
          cache: 'yarn'

      - name: Installing dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: Testing
        run: yarn test

      - name: Testing E2E
        run: yarn test:e2e
