name: Deploy development

on:
  pull_request:
    types:
      - labeled
    branches: [develop]
  push:
    branches: [develop]

# concurrency:
#   group: ${{ github.ref }}-${{ github.workflow }}
#   cancel-in-progress: true

jobs:
  build:
    if: ${{ (github.event.action != 'labeled' || github.event.label.name == 'deploy-dev') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3.1.1
        with:
          node-version: '16.X'
          cache: 'yarn'

      - name: Installing dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: Building
        run: yarn build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: development
      url: ${{ steps.deployment-result.outputs.status-url }}
    steps:
      - name: Remove deploy-dev label
        uses: actions-ecosystem/action-remove-labels@v1.3.0
        if: ${{ github.event.action == 'labeled' }}
        with:
          labels: |
            deploy-dev

      - name: Deploying
        run: echo Deploying...

      - name: Gather deployment result info
        id: deployment-result
        env:
          # TODO: Replace with `${{ secrets.DEV_API_URL }}/status` if possible.
          DEV_API_STATUS_URL: 'https://google.com'
        run: echo "::set-output name=status-url::$DEV_API_STATUS_URL"

  qa:
    needs: deploy
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    strategy:
      matrix:
        message: ${{ github.event.commits.*.message }}
    steps:
      - name: Check action
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo ${{ github.event.action }}
          echo "$GITHUB_CONTEXT"

      - name: Login to JIRA
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}

      - name: Find in commit messages
        id: find-ticket
        uses: atlassian/gajira-find-issue-key@master
        with:
          string: ${{ matrix.message }}
          from: ''

      - name: Transition ticket to in progress
        if: ${{ steps.find-ticket.outputs.issue }}
        uses: atlassian/gajira-transition@master
        with:
          issue: ${{ steps.find-ticket.outputs.issue }}
          transition: 'QA'
