
on: 
  pull_request:
    branches: [ develop ]
  push:
    branches: ['*']

name: Jira integrations

jobs:
  build:
    runs-on: ubuntu-latest
    name: In progress
    steps:
    - name: Login to JIRA
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}

    - name: Find in commit messages
      id: find-ticket
      uses: atlassian/gajira-find-issue-key@master
      with:
        from: commits

    - name: List found ticket
      run: echo ${{ steps.find-ticket.outputs.issue }}

    - name: Transition issue
      if: ${{ steps.find-ticket.outputs.issue }}
      uses: atlassian/gajira-transition@master
      with:
        issue: ${{ steps.find-ticket.outputs.issue }}
        transition: "In progress"
