
on: 
  push:
    branches: ['*']
  pull_request:
    branches: ['develop']
    types:
      - ready_for_review
      - opened

name: Jira integrations

jobs:
    # Pull_request event doesn't supply any commits reference except the link to the api 
  get-commits:
    name: Get commits
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.commits.outputs.matrix }}
    steps:
    - name: Check action
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo ${{ github.event.action }}
        echo "$GITHUB_CONTEXT"

    - name: Download commits
      id: commits
      run: |
        echo "::set-output name=matrix::{\"message\":$(curl ${{ github.event.pull_request._links.commits.href }} | jq -c 'map(.commit.message)')}"

    - name: Show commits
      run: |
        echo ${{ steps.commits.outputs.matrix }}

  in-progress:
    runs-on: ubuntu-latest
    name: JIRA In progress
    if: ${{ github.event.action == 'converted_to_draft' || github.event_name == 'push' }}
    needs: get-commits
    strategy:
      matrix: ${{ fromJson(needs.get-commits.outputs.matrix) || github.event.commits.*.message }}
    steps:
    - name: Login to JIRA
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}

    - name: Find in commit messages
      id: find-ticket
      uses: atlassian/gajira-find-issue-key@master
      with:
        string: |
          ${{ matrix.message }}

    - name: Transition ticket to in progress
      if: ${{ steps.find-ticket.outputs.issue }}
      uses: atlassian/gajira-transition@master
      with:
        issue: ${{ steps.find-ticket.outputs.issue }}
        transition: "In progress"

  done:
    if: ${{ github.event.action == 'ready_for_review' || github.event.action == 'opened' }}
    runs-on: ubuntu-latest
    needs: get-commits
    name: JIRA Done
    strategy:
      matrix: ${{ fromJson(needs.get-commits.outputs.matrix) }}
    steps:
    - name: Login to JIRA
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}

    - name: Find in commit messages
      id: find-ticket
      uses: atlassian/gajira-find-issue-key@master
      with:
        string: |
          ${{ matrix.message }}

    - name: Transition ticket to in progress
      if: ${{ steps.find-ticket.outputs.issue }}
      uses: atlassian/gajira-transition@master
      with:
        issue: ${{ steps.find-ticket.outputs.issue }}
        transition: "Done"
