on:
  push:
    branches-ignore: ['develop', 'main']

name: Jira push integrations

jobs:
  in-progress:
    runs-on: ubuntu-latest
    name: JIRA ticket In progress
    steps:
      - name: Login to JIRA
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}

      - name: Find in commit messages
        id: find-ticket
        uses: atlassian/gajira-find-issue-key@master
        with:
          string: ${{ join(github.event.commits.*.message, ' ') }}
          from: ''

      - name: Transition ticket to in progress
        if: ${{ steps.find-ticket.outputs.issue }}
        uses: atlassian/gajira-transition@master
        with:
          issue: ${{ steps.find-ticket.outputs.issue }}
          transition: 'In progress'
