# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main, CI/CD ]
  pull_request:
    branches: [ main, CI/CD ]

jobs:
  build:

    runs-on: ${{ matrix.runs-on }}

    strategy:
      matrix:
        node-version: [14.x]
        runs-on: [self-hosted, ubuntu-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Installing yarn
      run: npm install -g yarn
    
    - name: Installing dependencies
      run: yarn install
      
    - name: Prettifying
      run: yarn format
      
    - name: Linting
      run: yarn lint
      
    - name: Testing
      run: yarn test
      
    - name: Skipping Testing E2E
    
    - name: Building
      env: 
        NODE_ENV: development
      run: yarn build
